name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          mkdir -p builds
          GOOS=linux GOARCH=amd64 go build -o builds/gpt-term-linux-amd64 cmd/gpt-term/main.go
          GOOS=darwin GOARCH=amd64 go build -o builds/gpt-term-darwin-amd64 cmd/gpt-term/main.go
          GOOS=windows GOARCH=amd64 go build -o builds/gpt-term-windows-amd64.exe cmd/gpt-term/main.go

      - name: Generate SHA256 checksums
        run: |
          cd builds
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            builds/*
          generate_release_notes: true

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        run: |
          # Get the checksums
          DARWIN_SHA=$(grep darwin-amd64 builds/checksums.txt | awk '{print $1}')
          LINUX_SHA=$(grep linux-amd64 builds/checksums.txt | awk '{print $1}')
          
          # Clone homebrew repo
          git clone https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${{ github.repository_owner }}/homebrew-gpt-term.git
          cd homebrew-gpt-term
          
          # Create Formula directory if it doesn't exist
          mkdir -p Formula
          
          # Update formula
          cat > Formula/gpt-term.rb << EOL
          class GptTerm < Formula
            desc "CLI tool for GPT interactions in the terminal"
            homepage "https://github.com/${{ github.repository }}"
            version "${VERSION}"
            
            if OS.mac?
              url "https://github.com/${{ github.repository }}/releases/download/${VERSION}/gpt-term-darwin-amd64"
              sha256 "${DARWIN_SHA}"
            elsif OS.linux?
              url "https://github.com/${{ github.repository }}/releases/download/${VERSION}/gpt-term-linux-amd64"
              sha256 "${LINUX_SHA}"
            end
            
            def install
              bin.install "gpt-term-#{OS.mac? ? "darwin" : "linux"}-amd64" => "gpt-term"
            end
            
            test do
              system "#{bin}/gpt-term", "--version"
            end
          end
          EOL
          
          # Commit and push changes
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Formula/gpt-term.rb
          git commit -m "Update formula to ${VERSION}"
          git push
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}